version: "2.4"
services:
  reverse-proxy:
    image: "nginx:1.19-alpine"
    depends_on:
      - korogi-api
      - korogi-web
    links:
      - korogi-api:korogi-api
      - korogi-web:korogi-web
    volumes:
    - ./delivery/reverse-proxy/config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
  postgres:
    image: "postgres:12-alpine"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=korogi
      - POSTGRES_PASSWORD=korogi
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U korogi"]
      interval: 2s
      timeout: 5s
      retries: 10
  korogi-api:
    image: "korogi-api"
    depends_on:
      postgres:
        condition: service_healthy
    build: delivery/korogi-api
    volumes:
      - ./delivery/korogi-api/secrets:/etc/secrets:ro
      - ./logs:/opt/logs
    links:
      - postgres:korogi-postgres
    user: ${CURRENT_USER_UID}
  korogi-web:
    image: "korogi-web"
    build: delivery/korogi-web

volumes:
  postgres: { }