version: "2"
services:
  korogi:
    image: "korogi"
    depends_on:
      - korogi-postgres
      - keycloak
    restart: always
    build: .
    ports:
      - 8081:8080
      - 8788:8000
      - 8444:8443
    volumes:
      - ./delivery/config/korogi/certificates:/usr/local/tomcat/conf/certificates:ro
      - ./delivery/config/korogi/keycloak:/opt/keystore:ro
      - ./logs:/opt/logs
    env_file:
      - delivery/config/korogi/secrets/database.properties
      - delivery/config/korogi/secrets/keycloak.properties
    environment:
      - JPDA_ADDRESS=*:8000
      - JPDA_TRANSPORT=dt_socket
      - TZ=${KOROGI_TZ}
    links:
      - korogi-postgres:korogi-postgres
      - keycloak:keycloak
    entrypoint: catalina.sh
    command: jpda run
  korogi-postgres:
    image: "postgres:9.6-alpine"
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=korogi
      - POSTGRES_PASSWORD=korogi
  keycloak:
    image: "jboss/keycloak:9.0.0"
    restart: on-failure
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./delivery/config/keycloak/realms:/tmp/keycloak:ro
      - ./delivery/config/keycloak/certificates:/etc/x509/https:ro
    environment:
      - KEYCLOAK_USER=keycloak_admin
      - KEYCLOAK_PASSWORD=secret
      - KEYCLOAK_IMPORT=/tmp/keycloak/korogi-realm.json