version: "2"
services:
  korogi:
    image: "korogi"
    depends_on:
      - korogi-postgres
    restart: always
    build: .
    ports:
      - 8080:8080
      - 8787:8000
      - 8443:8443
    volumes:
      - ./config/certificates:/usr/local/tomcat/conf/certificates:ro
    env_file:
      - ./config/secrets/database.properties
    environment:
      - JPDA_ADDRESS=8000
      - JPDA_TRANSPORT=dt_socket
      - TZ=${KOROGI_TZ}
    links:
      - korogi-postgres:korogi-postgres
    entrypoint: catalina.sh
    command: jpda run
  korogi-postgres:
    image: "postgres:9.6-alpine"
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=korogi
      - POSTGRES_PASSWORD=korogi