version: "2"
services:
  reverse-proxy:
    image: "nginx:1.19-alpine"
    restart: on-failure
    depends_on:
      - korogi-api
      - korogi-web
    links:
      - korogi-api:korogi-api
      - korogi-web:korogi-web
    volumes:
    - ./delivery/reverse-proxy/config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
  postgres:
    image: "postgres:9.6-alpine"
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=korogi
      - POSTGRES_PASSWORD=korogi
  korogi-api:
    image: "korogi-api"
    depends_on:
      - postgres
    restart: always
    build: delivery/korogi-api
    volumes:
      - ./delivery/korogi-api/secrets:/etc/secrets:ro
      - ./logs:/opt/logs
    links:
      - postgres:korogi-postgres
  korogi-web:
    image: "korogi-web"
    restart: always
    build: delivery/korogi-web