korogi:
  oauth:
    token-secret: Korogi-local
    token-expiration-m-sec: 864000000
    front-end-return-url: "http://localhost:8080"
  encryption:
    key: DRzFcdL773M6UfeebRpvwNHuQaWMvAui

spring:
  datasource:
    password: korogi
    url: jdbc:postgresql://korogi-postgres:5432/postgres
    username: korogi
  flyway:
    user: korogi # DBA user
    password: korogi # DBA user
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 636747221147-eotnrnmv15nll3gov4c8slb60rgrur04.apps.googleusercontent.com
            client-secret: 7QMkZWHkl9fzBhoILxHOHiDI