logging:
  level:
    com:
      korogi:
        KorogiApplication: info
    root: warn
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: ${logging.pattern.console}

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info

server:
  forward-headers-strategy: framework

spring:
  hateoas:
    use-hal-as-default-json-media-type: false
  jpa:
    open-in-view: false
  mvc:
    servlet:
      path: /rest
  application:
    name: Korogi
