logging:
  level:
    com:
      korogi:
        KorogiApplication: info
    root: warn
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: ${logging.pattern.console}

spring:
  hateoas:
    use-hal-as-default-json-media-type: false
  jpa:
    open-in-view: false
