GRANT SELECT, INSERT, UPDATE, DELETE ON USERS TO ${read-user};
GRANT SELECT, INSERT, UPDATE, DELETE ON ROLES TO ${read-user};
GRANT SELECT, INSERT, UPDATE, DELETE ON ANIME TO ${read-user};
GRANT SELECT, INSERT, UPDATE, DELETE ON EPISODES TO ${read-user};
GRANT SELECT, INSERT, UPDATE, DELETE ON PERSONAGES TO ${read-user};