name: Compile and run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.3
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Compile
      run: mvn test-compile -B -PJenkins
    - name: Run tests
      run: mvn test -B -PJenkins -DskipNpmCi

  package:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.3
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Package
      run: mvn clean package -B -PJenkins
      
  build-push-docker:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build and push docker image
        uses: docker/build-push-action@v1.1.1
        with: 
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: daanpeelman/korogi
          tags: latest
          push: true
